/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AccountStatus = { 'active' : null } |
  { 'suspended' : null };
export interface Category {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface DashboardStats {
  'pendingPayments' : bigint,
  'totalOrders' : bigint,
  'totalUsers' : bigint,
  'totalRevenue' : Float,
}
export type Float = number;
export interface OrderRecord {
  'id' : bigint,
  'status' : OrderStatus,
  'serviceName' : string,
  'cost' : Float,
  'userId' : Principal,
  'link' : string,
  'createdAt' : bigint,
  'quantity' : bigint,
  'serviceId' : bigint,
}
export type OrderStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'processing' : null };
export interface PaymentRequest {
  'id' : bigint,
  'status' : PaymentStatus,
  'screenshotBlobId' : string,
  'userId' : Principal,
  'createdAt' : bigint,
  'adminNote' : string,
  'utrNumber' : string,
  'amount' : Float,
}
export type PaymentStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Service {
  'id' : bigint,
  'categoryId' : bigint,
  'pricePerThousand' : Float,
  'maxQuantity' : bigint,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'minQuantity' : bigint,
}
export interface Transaction {
  'id' : bigint,
  'transactionType' : TransactionType,
  'userId' : Principal,
  'createdAt' : bigint,
  'referenceId' : string,
  'description' : string,
  'amount' : Float,
}
export type TransactionType = { 'credit' : null } |
  { 'debit' : null };
export interface UserProfile {
  'accountStatus' : AccountStatus,
  'username' : string,
  'balance' : Float,
  'email' : string,
  'apiKey' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approvePayment' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCategory' : ActorMethod<[string, string], bigint>,
  'createService' : ActorMethod<
    [bigint, string, string, Float, bigint, bigint, boolean],
    bigint
  >,
  'deleteCategory' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getAllPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getAllServices' : ActorMethod<[], Array<Service>>,
  'getAllServicesAdmin' : ActorMethod<[], Array<Service>>,
  'getAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyOrders' : ActorMethod<[], Array<OrderRecord>>,
  'getMyPaymentRequests' : ActorMethod<[], Array<PaymentRequest>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[bigint, string, bigint], bigint>,
  'rejectPayment' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPaymentRequest' : ActorMethod<[string, string, Float], bigint>,
  'updateCategory' : ActorMethod<[bigint, string, string], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateService' : ActorMethod<
    [bigint, bigint, string, string, Float, bigint, bigint, boolean],
    undefined
  >,
  'updateServiceActiveStatus' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];