/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Float = IDL.Float64;
export const Category = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'processing' : IDL.Null,
});
export const OrderRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'serviceName' : IDL.Text,
  'cost' : Float,
  'userId' : IDL.Principal,
  'link' : IDL.Text,
  'createdAt' : IDL.Nat,
  'quantity' : IDL.Nat,
  'serviceId' : IDL.Nat,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const PaymentRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : PaymentStatus,
  'screenshotBlobId' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Nat,
  'adminNote' : IDL.Text,
  'utrNumber' : IDL.Text,
  'amount' : Float,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'pricePerThousand' : Float,
  'maxQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'minQuantity' : IDL.Nat,
});
export const AccountStatus = IDL.Variant({
  'active' : IDL.Null,
  'suspended' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'accountStatus' : AccountStatus,
  'username' : IDL.Text,
  'balance' : Float,
  'email' : IDL.Text,
  'apiKey' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'pendingPayments' : IDL.Nat,
  'totalOrders' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalRevenue' : Float,
});
export const TransactionType = IDL.Variant({
  'credit' : IDL.Null,
  'debit' : IDL.Null,
});
export const Transaction = IDL.Record({
  'id' : IDL.Nat,
  'transactionType' : TransactionType,
  'userId' : IDL.Principal,
  'createdAt' : IDL.Nat,
  'referenceId' : IDL.Text,
  'description' : IDL.Text,
  'amount' : Float,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approvePayment' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createService' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Float, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [], []),
  'deleteService' : IDL.Func([IDL.Nat], [], []),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getAllPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllServicesAdmin' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getMyOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
  'getMyPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
  'rejectPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPaymentRequest' : IDL.Func([IDL.Text, IDL.Text, Float], [IDL.Nat], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateService' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Text, IDL.Text, Float, IDL.Nat, IDL.Nat, IDL.Bool],
      [],
      [],
    ),
  'updateServiceActiveStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Float = IDL.Float64;
  const Category = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const OrderRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'serviceName' : IDL.Text,
    'cost' : Float,
    'userId' : IDL.Principal,
    'link' : IDL.Text,
    'createdAt' : IDL.Nat,
    'quantity' : IDL.Nat,
    'serviceId' : IDL.Nat,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const PaymentRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : PaymentStatus,
    'screenshotBlobId' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Nat,
    'adminNote' : IDL.Text,
    'utrNumber' : IDL.Text,
    'amount' : Float,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'pricePerThousand' : Float,
    'maxQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'minQuantity' : IDL.Nat,
  });
  const AccountStatus = IDL.Variant({
    'active' : IDL.Null,
    'suspended' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'accountStatus' : AccountStatus,
    'username' : IDL.Text,
    'balance' : Float,
    'email' : IDL.Text,
    'apiKey' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'pendingPayments' : IDL.Nat,
    'totalOrders' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalRevenue' : Float,
  });
  const TransactionType = IDL.Variant({
    'credit' : IDL.Null,
    'debit' : IDL.Null,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Nat,
    'transactionType' : TransactionType,
    'userId' : IDL.Principal,
    'createdAt' : IDL.Nat,
    'referenceId' : IDL.Text,
    'description' : IDL.Text,
    'amount' : Float,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approvePayment' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createService' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Float, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [], []),
    'deleteService' : IDL.Func([IDL.Nat], [], []),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getAllPaymentRequests' : IDL.Func(
        [],
        [IDL.Vec(PaymentRequest)],
        ['query'],
      ),
    'getAllServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllServicesAdmin' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, UserProfile))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getMyOrders' : IDL.Func([], [IDL.Vec(OrderRecord)], ['query']),
    'getMyPaymentRequests' : IDL.Func([], [IDL.Vec(PaymentRequest)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat], [IDL.Nat], []),
    'rejectPayment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPaymentRequest' : IDL.Func(
        [IDL.Text, IDL.Text, Float],
        [IDL.Nat],
        [],
      ),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateService' : IDL.Func(
        [
          IDL.Nat,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Float,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
        ],
        [],
        [],
      ),
    'updateServiceActiveStatus' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };